// TEMPORARY DATA

export let role = "student";

export const teachersData = [
  {
    id: 1,
    teacherId: "1001",
    name: "Ali Raza",
    email: "ali.raza@school.pk",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03001234567",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", ],
    address: "Gulshan-e-Iqbal, Karachi",
  },
  {
    id: 2,
    teacherId: "1002",
    name: "Fatima Khan",
    email: "fatima.khan@school.pk",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03111234567",
    subjects: ["Physics", "Chemistry"],
    classes: [ "4B", "3C"],
    address: "Johar Town, Lahore",
  },
  {
    id: 3,
    teacherId: "1003",
    name: "Sana Ahmed",
    email: "sana.ahmed@school.pk",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03211234567",
    subjects: ["Biology"],
    classes: ["5A",  "3C"],
    address: "Satellite Town, Rawalpindi",
  },
  {
    id: 4,
    teacherId: "1004",
    name: "Usman Javed",
    email: "usman.javed@school.pk",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03331234567",
    subjects: ["History"],
    classes: ["5A", "4B"],
    address: "Model Town, Lahore",
  },
  {
    id: 5,
    teacherId: "1005",
    name: "Hina Malik",
    email: "hina.malik@school.pk",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03011234567",
    subjects: ["Music", "History"],
    classes: ["5A", "4B"],
    address: "F-11, Islamabad",
  },
  {
    id: 6,
    teacherId: "1006",
    name: "Zainab Rauf",
    email: "zainab.rauf@school.pk",
    photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03451234567",
    subjects: ["Physics"],
    classes: ["5A", "3C"],
    address: "Shah Faisal Colony, Karachi",
  },
  {
    id: 7,
    teacherId: "1007",
    name: "Hamza Ali",
    email: "hamza.ali@school.pk",
    photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03151234567",
    subjects: ["English", "Urdu"],
    classes: [ "4B", "3C"],
    address: "Garden Town, Lahore",
  },
  {
    id: 8,
    teacherId: "1008",
    name: "Mehwish Tariq",
    email: "mehwish.tariq@school.pk",
    photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03341234567",
    subjects: ["Math", "Computer Science"],
    classes: ["5A",  "3C"],
    address: "G-10, Islamabad",
  },
  {
    id: 9,
    teacherId: "1009",
    name: "Imran Sheikh",
    email: "imran.sheikh@school.pk",
    photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03031234567",
    subjects: ["English Literature", "English"],
    classes: ["5A",  "3C"],
    address: "Defence, Karachi",
  },
  {
    id: 10,
    teacherId: "1010",
    name: "Rabia Shah",
    email: "rabia.shah@school.pk",
    photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03221234567",
    subjects: ["Biology"],
    classes: [ "4B", "3C"],
    address: "Iqbal Town, Lahore",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "2001",
    name: "Ahmed Ali",
    email: "ahmed.ali@student.pk",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03001234567",
    grade: 1,
    class: "1A",
    address: "Gulshan-e-Iqbal, Karachi",
  },
  {
    id: 2,
    studentId: "2002",
    name: "Fatima Shah",
    email: "fatima.shah@student.pk",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03111234567",
    grade: 2,
    class: "2B",
    address: "Johar Town, Lahore",
  },
  {
    id: 3,
    studentId: "2003",
    name: "Zain Raza",
    email: "zain.raza@student.pk",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03211234567",
    grade: 3,
    class: "3C",
    address: "Satellite Town, Rawalpindi",
  },
  {
    id: 4,
    studentId: "2004",
    name: "Hira Khalid",
    email: "hira.khalid@student.pk",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03331234567",
    grade: 4,
    class: "4A",
    address: "Model Town, Lahore",
  },
  {
    id: 5,
    studentId: "2005",
    name: "Ahsan Malik",
    email: "ahsan.malik@student.pk",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03011234567",
    grade: 5,
    class: "5B",
    address: "F-11, Islamabad",
  },
  {
    id: 6,
    studentId: "2006",
    name: "Mehak Tariq",
    email: "mehak.tariq@student.pk",
    photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03451234567",
    grade: 6,
    class: "6C",
    address: "Shah Faisal Colony, Karachi",
  },
  {
    id: 7,
    studentId: "2007",
    name: "Hamza Noor",
    email: "hamza.noor@student.pk",
    photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03151234567",
    grade: 7,
    class: "7A",
    address: "Garden Town, Lahore",
  },
  {
    id: 8,
    studentId: "2008",
    name: "Sana Rizvi",
    email: "sana.rizvi@student.pk",
    photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03341234567",
    grade: 8,
    class: "8B",
    address: "G-10, Islamabad",
  },
  {
    id: 9,
    studentId: "2009",
    name: "Bilal Javed",
    email: "bilal.javed@student.pk",
    photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03031234567",
    grade: 9,
    class: "9C",
    address: "Defence, Karachi",
  },
  {
    id: 10,
    studentId: "2010",
    name: "Rabia Mehmood",
    email: "rabia.mehmood@student.pk",
    photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "03221234567",
    grade: 10,
    class: "10A",
    address: "Iqbal Town, Lahore",
  },
];



export const parentsData = [
  {
    id: 1,
    name: "Ali Raza",
    students: ["Ahmed Ali"],
    email: "ali.raza@parent.pk",
    phone: "03001234567",
    address: "Gulshan-e-Iqbal, Karachi",
  },
  {
    id: 2,
    name: "Shazia Noor",
    students: ["Fatima Shah"],
    email: "shazia.noor@parent.pk",
    phone: "03111234567",
    address: "Johar Town, Lahore",
  },
  {
    id: 3,
    name: "Tariq Mehmood",
    students: ["Zain Raza"],
    email: "tariq.mehmood@parent.pk",
    phone: "03211234567",
    address: "Satellite Town, Rawalpindi",
  },
  {
    id: 4,
    name: "Khalid Bashir",
    students: ["Hira Khalid", "Ahsan Malik"],
    email: "khalid.bashir@parent.pk",
    phone: "03331234567",
    address: "Model Town, Lahore",
  },
  {
    id: 5,
    name: "Farzana Tariq",
    students: ["Mehak Tariq"],
    email: "farzana.tariq@parent.pk",
    phone: "03011234567",
    address: "Shah Faisal Colony, Karachi",
  },
  {
    id: 6,
    name: "Noor Hassan",
    students: ["Hamza Noor"],
    email: "noor.hassan@parent.pk",
    phone: "03451234567",
    address: "Garden Town, Lahore",
  },
  {
    id: 7,
    name: "Rizwan Ahmed",
    students: ["Sana Rizvi", "Bilal Javed"],
    email: "rizwan.ahmed@parent.pk",
    phone: "03151234567",
    address: "G-10, Islamabad",
  },
  {
    id: 8,
    name: "Rubina Ashraf",
    students: ["Rabia Mehmood"],
    email: "rubina.ashraf@parent.pk",
    phone: "03341234567",
    address: "Iqbal Town, Lahore",
  },
  {
    id: 9,
    name: "Javed Iqbal",
    students: ["Ophelia Castro"],
    email: "javed.iqbal@parent.pk",
    phone: "03031234567",
    address: "Defence, Karachi",
  },
  {
    id: 10,
    name: "Mehmood Ghauri",
    students: ["Allen Black"],
    email: "mehmood.ghauri@parent.pk",
    phone: "03221234567",
    address: "F-11, Islamabad",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Ali Khan", "Fatima Rizvi"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Sana Malik", "Tariq Mehmood"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Hassan Raza", "Nida Anwar"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Zara Iqbal", "Waqas Shah"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Rabia Aslam", "Furqan Haider"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Ayesha Nawaz", "Rauf Siddiqui"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Sadia Yousaf", "Imran Latif"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Hira Zubair", "Talha Qureshi"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Rameen Junaid", "Adeel Shabbir"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Zainab Saeed", "Bilal Ahmed"],
  },
];


export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Ali Raza",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Sana Sheikh",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Umar Farooq",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Maria Imran",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Hamza Shahid",
  },
  {
    id: 6,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Areeba Khalid",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Noman Tariq",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Kinza Qasim",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Bilal Arshad",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Mehwish Ahmed",
  },
];


export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Ahmed Nawaz",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Zainab Tariq",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Faisal Khan",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Samina Arif",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Ahsan Qureshi",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Hira Iqbal",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Tariq Mehmood",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Saima Rauf",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Bilal Aslam",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Nimra Zafar",
  },
];


export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Ahmed Nawaz",
    date: "2025-07-15",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Zainab Tariq",
    date: "2025-07-16",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Faisal Khan",
    date: "2025-07-17",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Samina Arif",
    date: "2025-07-18",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Ahsan Qureshi",
    date: "2025-07-19",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Hira Iqbal",
    date: "2025-07-20",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Tariq Mehmood",
    date: "2025-07-21",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Saima Rauf",
    date: "2025-07-22",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Bilal Aslam",
    date: "2025-07-23",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Nimra Zafar",
    date: "2025-07-24",
  },
];


export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Ahmed Nawaz",
    dueDate: "2025-07-15",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Zainab Tariq",
    dueDate: "2025-07-16",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Faisal Khan",
    dueDate: "2025-07-17",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Samina Arif",
    dueDate: "2025-07-18",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Ahsan Qureshi",
    dueDate: "2025-07-19",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Hira Iqbal",
    dueDate: "2025-07-20",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Tariq Mehmood",
    dueDate: "2025-07-21",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Saima Rauf",
    dueDate: "2025-07-22",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Bilal Aslam",
    dueDate: "2025-07-23",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Nimra Zafar",
    dueDate: "2025-07-24",
  },
];


export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Ahmed Khan",
    student: "Ali Raza",
    date: "2025-07-15",
    type: "exam",
    score: 92,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Sana Sheikh",
    student: "Fatima Noor",
    date: "2025-07-15",
    type: "exam",
    score: 85,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Zainab Bukhari",
    student: "Hassan Ali",
    date: "2025-07-15",
    type: "exam",
    score: 76,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bilal Qureshi",
    student: "Ayesha Tariq",
    date: "2025-07-15",
    type: "exam",
    score: 89,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Rabia Imran",
    student: "Zain Rafiq",
    date: "2025-07-15",
    type: "exam",
    score: 78,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Shoaib Malik",
    student: "Iqra Aslam",
    date: "2025-07-15",
    type: "exam",
    score: 88,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Nimra Hussain",
    student: "Taha Naveed",
    date: "2025-07-15",
    type: "exam",
    score: 69,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Imran Farooq",
    student: "Mehak Zafar",
    date: "2025-07-15",
    type: "exam",
    score: 94,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Fahad Rizvi",
    student: "Usman Shah",
    date: "2025-07-15",
    type: "exam",
    score: 80,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Areeba Sultan",
    student: "Laiba Khan",
    date: "2025-07-15",
    type: "exam",
    score: 98,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-07-15",
    startTime: "09:00",
    endTime: "10:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-07-15",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-07-15",
    startTime: "11:00",
    endTime: "12:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-07-15",
    startTime: "12:00",
    endTime: "13:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-07-15",
    startTime: "13:00",
    endTime: "14:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-07-15",
    startTime: "14:00",
    endTime: "15:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-07-15",
    startTime: "15:00",
    endTime: "16:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-07-15",
    startTime: "16:00",
    endTime: "17:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-07-15",
    startTime: "17:00",
    endTime: "18:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-07-15",
    startTime: "18:00",
    endTime: "19:00",
  },
];


export const announcementsData = [
  {
    id: 1,
    title: "4A Math Test Rescheduled",
    class: "4A",
    date: "2025-07-15",
  },
  {
    id: 2,
    title: "3A Math Test Reminder",
    class: "3A",
    date: "2025-07-15",
  },
  {
    id: 3,
    title: "3B Math Assignment Deadline",
    class: "3B",
    date: "2025-07-15",
  },
  {
    id: 4,
    title: "6A Math Quiz Tomorrow",
    class: "6A",
    date: "2025-07-15",
  },
  {
    id: 5,
    title: "8C Weekly Math Practice",
    class: "8C",
    date: "2025-07-15",
  },
  {
    id: 6,
    title: "2A Math Homework Submission",
    class: "2A",
    date: "2025-07-15",
  },
  {
    id: 7,
    title: "4C Math Syllabus Revision",
    class: "4C",
    date: "2025-07-15",
  },
  {
    id: 8,
    title: "4B Extra Math Class Notification",
    class: "4B",
    date: "2025-07-15",
  },
  {
    id: 9,
    title: "3C Math Project Guidelines",
    class: "3C",
    date: "2025-07-15",
  },
  {
    id: 10,
    title: "1C Math Test Schedule",
    class: "1C",
    date: "2025-07-15",
  },
];



// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 6, 16, 8, 0),
    end: new Date(2025, 6, 16, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 6, 16, 9, 0),
    end: new Date(2025, 6, 16, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 6, 16, 10, 0),
    end: new Date(2025, 6, 16, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 6, 16, 11, 0),
    end: new Date(2025, 6, 16, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 6, 16, 13, 0),
    end: new Date(2025, 6, 16, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 16, 14, 0),
    end: new Date(2025, 6, 16, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 6, 17, 9, 0),
    end: new Date(2025, 6, 17, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 6, 17, 10, 0),
    end: new Date(2025, 6, 17, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 6, 17, 11, 0),
    end: new Date(2025, 6, 17, 11, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 17, 14, 0),
    end: new Date(2025, 6, 17, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 6, 18, 8, 0),
    end: new Date(2025, 6, 18, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 6, 18, 10, 0),
    end: new Date(2025, 6, 18, 10, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 6, 18, 13, 0),
    end: new Date(2025, 6, 18, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 18, 14, 0),
    end: new Date(2025, 6, 18, 14, 45), 
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 6, 19, 9, 0),
    end: new Date(2025, 6, 19, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 6, 19, 10, 0),
    end: new Date(2025, 6, 19, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 6, 19, 11, 0),
    end: new Date(2025, 6, 19, 11, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 19, 14, 0),
    end: new Date(2025, 6, 19, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 6, 20, 8, 0),
    end: new Date(2025, 6, 20, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 6, 20, 9, 0),
    end: new Date(2025, 6, 20, 9, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 6, 20, 11, 0),
    end: new Date(2025, 6, 20, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 6, 20, 13, 0),
    end: new Date(2025, 6, 20, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 20, 14, 0),
    end: new Date(2025, 6, 20, 14, 45),
  },
];
